# Generated by Django 5.2.10 on 2026-03-05 04:38

import django.db.models.deletion
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="O'quv yili, masalan: 2024-2025", max_length=50)),
                ('title_uz', models.CharField(help_text="O'quv yili, masalan: 2024-2025", max_length=50, null=True)),
                ('title_ru', models.CharField(help_text="O'quv yili, masalan: 2024-2025", max_length=50, null=True)),
                ('title_en', models.CharField(help_text="O'quv yili, masalan: 2024-2025", max_length=50, null=True)),
                ('badge_text', models.CharField(blank=True, help_text='Badge matni, masalan: QABUL 2024 BOSHLANDI', max_length=100)),
                ('badge_text_uz', models.CharField(blank=True, help_text='Badge matni, masalan: QABUL 2024 BOSHLANDI', max_length=100, null=True)),
                ('badge_text_ru', models.CharField(blank=True, help_text='Badge matni, masalan: QABUL 2024 BOSHLANDI', max_length=100, null=True)),
                ('badge_text_en', models.CharField(blank=True, help_text='Badge matni, masalan: QABUL 2024 BOSHLANDI', max_length=100, null=True)),
                ('hero_title', models.CharField(blank=True, help_text='Bosh sarlavha, masalan: Kelajagingizni biz bilan quring', max_length=255)),
                ('hero_title_uz', models.CharField(blank=True, help_text='Bosh sarlavha, masalan: Kelajagingizni biz bilan quring', max_length=255, null=True)),
                ('hero_title_ru', models.CharField(blank=True, help_text='Bosh sarlavha, masalan: Kelajagingizni biz bilan quring', max_length=255, null=True)),
                ('hero_title_en', models.CharField(blank=True, help_text='Bosh sarlavha, masalan: Kelajagingizni biz bilan quring', max_length=255, null=True)),
                ('hero_description', models.TextField(blank=True, help_text='Bosh tavsif matni')),
                ('hero_description_uz', models.TextField(blank=True, help_text='Bosh tavsif matni', null=True)),
                ('hero_description_ru', models.TextField(blank=True, help_text='Bosh tavsif matni', null=True)),
                ('hero_description_en', models.TextField(blank=True, help_text='Bosh tavsif matni', null=True)),
                ('apply_link', models.URLField(default='https://my.uzbmb.uz/', help_text='Hujjat topshirish havolasi', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (Saytda ko'rinadi)")),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qabul yili',
                'verbose_name_plural': 'Qabul yillari',
                'ordering': ['order', '-title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(help_text='Bosqich raqami, masalan: 01, 02', max_length=10)),
                ('title', models.CharField(help_text='Bosqich nomi', max_length=255)),
                ('title_uz', models.CharField(help_text='Bosqich nomi', max_length=255, null=True)),
                ('title_ru', models.CharField(help_text='Bosqich nomi', max_length=255, null=True)),
                ('title_en', models.CharField(help_text='Bosqich nomi', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text="Bosqich haqida qisqacha ma'lumot")),
                ('description_uz', models.TextField(blank=True, help_text="Bosqich haqida qisqacha ma'lumot", null=True)),
                ('description_ru', models.TextField(blank=True, help_text="Bosqich haqida qisqacha ma'lumot", null=True)),
                ('description_en', models.TextField(blank=True, help_text="Bosqich haqida qisqacha ma'lumot", null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.ForeignKey(help_text='Tegishli qabul yili', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='admission.admissionyear')),
            ],
            options={
                'verbose_name': 'Qabul bosqichi',
                'verbose_name_plural': 'Qabul bosqichlari',
                'ordering': ['order', 'step_number'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='AdmissionQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_name', models.CharField(help_text="Ta'lim yo'nalishi nomi", max_length=255)),
                ('direction_name_uz', models.CharField(help_text="Ta'lim yo'nalishi nomi", max_length=255, null=True)),
                ('direction_name_ru', models.CharField(help_text="Ta'lim yo'nalishi nomi", max_length=255, null=True)),
                ('direction_name_en', models.CharField(help_text="Ta'lim yo'nalishi nomi", max_length=255, null=True)),
                ('language', models.CharField(help_text="Ta'lim tili, masalan: O'zbek, Rus, O'zbek/Rus", max_length=100)),
                ('language_uz', models.CharField(help_text="Ta'lim tili, masalan: O'zbek, Rus, O'zbek/Rus", max_length=100, null=True)),
                ('language_ru', models.CharField(help_text="Ta'lim tili, masalan: O'zbek, Rus, O'zbek/Rus", max_length=100, null=True)),
                ('language_en', models.CharField(help_text="Ta'lim tili, masalan: O'zbek, Rus, O'zbek/Rus", max_length=100, null=True)),
                ('grant_count', models.PositiveIntegerField(default=0, help_text="Grant o'rinlar soni")),
                ('contract_count', models.PositiveIntegerField(default=0, help_text="Kontrakt o'rinlar soni")),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.ForeignKey(help_text='Tegishli qabul yili', on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='admission.admissionyear')),
            ],
            options={
                'verbose_name': 'Qabul kvotasi',
                'verbose_name_plural': 'Qabul kvotalari',
                'ordering': ['order', 'direction_name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
