# Generated by Django 5.2.10 on 2026-03-05 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionStep',
        ),
    ]
