# Generated by Django 5.2.10 on 2026-02-06 09:44

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introduction text for the news page')),
            ],
            options={
                'verbose_name': 'News Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='University News Bot', help_text='Bot display name', max_length=100)),
                ('bot_token', models.CharField(blank=True, help_text='Telegram Bot API token from @BotFather', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret for webhook verification', max_length=255)),
                ('channel_id', models.BigIntegerField(blank=True, help_text='Telegram channel ID to sync from', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable bot integration')),
                ('auto_publish', models.BooleanField(default=True, help_text='Automatically publish synced posts (or save as draft)')),
                ('news_hashtags', models.CharField(default='#yangilik,#news,#новость', help_text='Comma-separated hashtags that indicate news', max_length=255)),
                ('announcement_hashtags', models.CharField(default='#elon,#announcement,#объявление', help_text='Comma-separated hashtags that indicate announcements', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Bot Config',
                'verbose_name_plural': 'Telegram Bot Configs',
            },
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('post_type', models.CharField(choices=[('news', 'Yangilik (News)'), ('announcement', "E'lon (Announcement)")], default='news', help_text='Type of post: news or announcement', max_length=20)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for listing pages', max_length=500)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Full content of the news/announcement')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when this was published')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin this item to top of listings')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='Telegram message ID if synced from Telegram', null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, help_text='Telegram chat/channel ID', null=True)),
                ('synced_from_telegram', models.BooleanField(default=False, help_text='Whether this was created from Telegram')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Main cover image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News/Announcement',
                'verbose_name_plural': 'News/Announcements',
                'ordering': ['-is_pinned', '-published_date'],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('news', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='news.newspage')),
            ],
            options={
                'verbose_name': 'News Image',
                'verbose_name_plural': 'News Images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField()),
                ('telegram_chat_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Raw Telegram message data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_logs', to='news.newspage')),
            ],
            options={
                'verbose_name': 'Telegram Sync Log',
                'verbose_name_plural': 'Telegram Sync Logs',
                'unique_together': {('telegram_message_id', 'telegram_chat_id')},
            },
        ),
    ]
