# Generated by Django 5.2.10 on 2026-02-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotconfig',
            name='admin_user_ids',
            field=models.TextField(blank=True, help_text='Comma-separated Telegram user IDs of admins who can post news (leave empty to allow all)'),
        ),
    ]
