# Generated by Django 5.2.10 on 2026-02-07 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_telegrambotconfig_admin_user_ids'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotconfig',
            name='default_announcement_image',
            field=models.ForeignKey(blank=True, help_text='Default cover image for announcements without photos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='telegrambotconfig',
            name='default_news_image',
            field=models.ForeignKey(blank=True, help_text='Default cover image for news without photos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
