# Generated by Django 5.2.12 on 2026-03-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_telegrambotconfig_default_announcement_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotconfig',
            name='website_url',
            field=models.URLField(default='https://example.com', help_text="Base URL of the website (for 'View on Website' button in bot)", max_length=255),
        ),
    ]
