# Generated by Django 5.2.10 on 2026-02-21 07:46

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Kategoriya nomi, masalan: O'quv faoliyati", max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL uchun identifikator (avtomatik yaratiladi)', max_length=255, unique=True)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text="Kategoriya haqida umumiy ma'lumot")),
                ('icon', models.CharField(blank=True, help_text='Ikonka CSS klassi yoki emoji (masalan: 🎓 yoki fa-book)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Kategoriya uchun muqova rasm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Faoliyat kategoriyasi',
                'verbose_name_plural': 'Faoliyat kategoriyalari',
                'ordering': ['order', 'title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sahifa sarlavhasi', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL uchun identifikator (avtomatik yaratiladi)', max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni')),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Tegishli kategoriya', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='activities.activitycategory')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Sahifa uchun muqova rasm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('parent', models.ForeignKey(blank=True, help_text="Yuqori sahifa (bo'sh = kategoriyaning to'g'ridan-to'g'ri bolasi)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='activities.activitypage')),
            ],
            options={
                'verbose_name': 'Faoliyat sahifasi',
                'verbose_name_plural': 'Faoliyat sahifalari',
                'ordering': ['order', 'title'],
                'unique_together': {('category', 'slug')},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
