# Generated by Django 5.2.10 on 2026-03-03 08:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycategory',
            name='description_en',
            field=wagtail.fields.RichTextField(blank=True, help_text="Kategoriya haqida umumiy ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='description_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text="Kategoriya haqida umumiy ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='description_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text="Kategoriya haqida umumiy ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='title_en',
            field=models.CharField(help_text="Kategoriya nomi, masalan: O'quv faoliyati", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='title_ru',
            field=models.CharField(help_text="Kategoriya nomi, masalan: O'quv faoliyati", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='title_uz',
            field=models.CharField(help_text="Kategoriya nomi, masalan: O'quv faoliyati", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='content_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni', null=True),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='content_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni', null=True),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='content_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni', null=True),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='title_en',
            field=models.CharField(help_text='Sahifa sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='title_ru',
            field=models.CharField(help_text='Sahifa sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activitypage',
            name='title_uz',
            field=models.CharField(help_text='Sahifa sarlavhasi', max_length=255, null=True),
        ),
    ]
