# Generated by Django 5.2.10 on 2026-02-02 04:24

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FacultyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('faculty_code', models.CharField(blank=True, max_length=20)),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_location', models.CharField(blank=True, max_length=255)),
                ('dean_name', models.CharField(blank=True, max_length=255)),
                ('dean_title', models.CharField(blank=True, max_length=255)),
                ('dean_bio', wagtail.fields.RichTextField(blank=True)),
                ('content_blocks', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('statistics', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('label', 3), ('value', 3)]], {})})),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('dean_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='FacultyDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('head_of_department', models.CharField(blank=True, max_length=255)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('faculty', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='faculties.facultypage')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_faculties_facultydepartment')],
            },
        ),
        migrations.CreateModel(
            name='FacultyAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('faculty', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='faculties.facultypage')),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_faculties_facultyachievement')],
            },
        ),
    ]
