# Generated by Django 5.2.10 on 2026-02-04 09:58

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DepartmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('department_code', models.CharField(blank=True, max_length=20)),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('office_location', models.CharField(blank=True, max_length=255)),
                ('head_name', models.CharField(blank=True, max_length=255)),
                ('head_title', models.CharField(blank=True, max_length=255)),
                ('head_bio', wagtail.fields.RichTextField(blank=True)),
                ('content_blocks', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('statistics', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('label', 3), ('value', 3)]], {})})),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_departments', to='faculties.facultypage')),
                ('head_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='DepartmentProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('program_type', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='bachelor', max_length=20)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('department', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='faculties.departmentpage')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_faculties_departmentprogram')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('journal_or_conference', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('department', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='faculties.departmentpage')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_faculties_departmentpublication')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('bio', wagtail.fields.RichTextField(blank=True)),
                ('department', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='faculties.departmentpage')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'verbose_name_plural': 'Department Staff',
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_faculties_departmentstaff')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('both', 'Both')], default='bachelor', max_length=20)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('department', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='faculties.departmentpage')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_faculties_departmentsubject')],
            },
        ),
    ]
