# Generated by Django 5.2.12 on 2026-03-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentprogram',
            name='description',
        ),
        migrations.RemoveField(
            model_name='departmentprogram',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='departmentprogram',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='departmentprogram',
            name='description_uz',
        ),
        migrations.AddField(
            model_name='department',
            name='reception_time',
            field=models.CharField(blank=True, help_text='Qabul vaqti', max_length=255),
        ),
        migrations.AddField(
            model_name='department',
            name='reception_time_en',
            field=models.CharField(blank=True, help_text='Qabul vaqti', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='reception_time_ru',
            field=models.CharField(blank=True, help_text='Qabul vaqti', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='reception_time_uz',
            field=models.CharField(blank=True, help_text='Qabul vaqti', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departmentprogram',
            name='degree',
            field=models.CharField(choices=[('bachelor', 'Bakalavriat'), ('master', 'Magistratura')], default='bachelor', help_text="Ta'lim darajasi", max_length=20),
        ),
    ]
