# Generated by Django 5.2.12 on 2026-05-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculties', '0003_facultystaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaff',
            name='degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='departmentstaff',
            name='degree_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departmentstaff',
            name='degree_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departmentstaff',
            name='degree_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facultystaff',
            name='degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='facultystaff',
            name='degree_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facultystaff',
            name='degree_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facultystaff',
            name='degree_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
