# Generated by Django 5.2.10 on 2026-02-11 09:28

import django.db.models.deletion
import django.utils.timezone
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Vakansiya nomi, masalan: Katta O'qituvchi", max_length=255)),
                ('department', models.CharField(help_text="Bo'lim yoki kafedra nomi", max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', "To'liq stavka"), ('part_time', 'Yarim stavka')], default='full_time', help_text='Ish turi', max_length=20)),
                ('category', models.CharField(choices=[('academic', 'Pedagogik'), ('technical', 'Texnik'), ('admin', "Ma'muriy")], default='academic', help_text='Vakansiya toifasi', max_length=20)),
                ('salary_min', models.PositiveIntegerField(default=0, help_text="Minimal ish haqi (so'm)")),
                ('salary_max', models.PositiveIntegerField(default=0, help_text="Maksimal ish haqi (so'm)")),
                ('description', wagtail.fields.RichTextField(blank=True, help_text="Vakansiya haqida to'liq ma'lumot")),
                ('requirements', wagtail.fields.RichTextField(blank=True, help_text='Talablar')),
                ('is_active', models.BooleanField(default=True, help_text='Vakansiya faolmi?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="To'liq ism-sharif", max_length=255)),
                ('phone', models.CharField(help_text='Telefon raqam', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Elektron pochta (ixtiyoriy)', max_length=254)),
                ('resume', models.FileField(blank=True, help_text='Rezyume fayl (ixtiyoriy)', null=True, upload_to='vacancy_resumes/%Y/%m/')),
                ('cover_letter', models.TextField(blank=True, help_text="Qo'shimcha xabar (ixtiyoriy)")),
                ('is_read', models.BooleanField(default=False, help_text="Admin ko'rganmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(help_text='Qaysi vakansiyaga ariza', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='common.vacancy')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
