# Generated by Django 5.2.10 on 2026-02-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyapplication',
            name='resume',
            field=models.FileField(default='', help_text="Ma'lumotnoma fayl (PDF, DOC, DOCX)", upload_to='vacancy_resumes/%Y/%m/'),
            preserve_default=False,
        ),
    ]
