# Generated by Django 5.2.10 on 2026-03-03 08:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_vacancyapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='department_en',
            field=models.CharField(help_text="Bo'lim yoki kafedra nomi", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='department_ru',
            field=models.CharField(help_text="Bo'lim yoki kafedra nomi", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='department_uz',
            field=models.CharField(help_text="Bo'lim yoki kafedra nomi", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=wagtail.fields.RichTextField(blank=True, help_text="Vakansiya haqida to'liq ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text="Vakansiya haqida to'liq ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text="Vakansiya haqida to'liq ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Talablar', null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text='Talablar', null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text='Talablar', null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(help_text="Vakansiya nomi, masalan: Katta O'qituvchi", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(help_text="Vakansiya nomi, masalan: Katta O'qituvchi", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_uz',
            field=models.CharField(help_text="Vakansiya nomi, masalan: Katta O'qituvchi", max_length=255, null=True),
        ),
    ]
