# Generated by Django 5.2.12 on 2026-03-17 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('link', models.URLField(verbose_name='Havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('short_description', models.TextField(verbose_name='Qisqacha tavsif')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name="Ikonka (ixtiyoriy, default frontend'da ishlatiladi)")),
            ],
            options={
                'verbose_name': 'Axborot tizimi',
                'verbose_name_plural': 'Axborot tizimlari',
                'ordering': ['order', 'name'],
            },
        ),
    ]
