# Generated by Django 5.2.12 on 2026-03-16 05:54

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Bo'lim sarlavhasi", max_length=255)),
                ('title_uz', models.CharField(help_text="Bo'lim sarlavhasi", max_length=255, null=True)),
                ('title_ru', models.CharField(help_text="Bo'lim sarlavhasi", max_length=255, null=True)),
                ('title_en', models.CharField(help_text="Bo'lim sarlavhasi", max_length=255, null=True)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text="Bo'lim mazmuni")),
                ('content_uz', wagtail.fields.RichTextField(blank=True, help_text="Bo'lim mazmuni", null=True)),
                ('content_ru', wagtail.fields.RichTextField(blank=True, help_text="Bo'lim mazmuni", null=True)),
                ('content_en', wagtail.fields.RichTextField(blank=True, help_text="Bo'lim mazmuni", null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ForeignKey(blank=True, help_text="Bo'lim uchun rasm", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': "Yutuq bo'limi",
                'verbose_name_plural': 'Yutuqlar',
                'ordering': ['order', 'title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Klub nomi, masalan: Zakovat Klub', max_length=255)),
                ('name_uz', models.CharField(help_text='Klub nomi, masalan: Zakovat Klub', max_length=255, null=True)),
                ('name_ru', models.CharField(help_text='Klub nomi, masalan: Zakovat Klub', max_length=255, null=True)),
                ('name_en', models.CharField(help_text='Klub nomi, masalan: Zakovat Klub', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL uchun identifikator (avtomatik yaratiladi)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Qisqacha tavsif (kartochka uchun)')),
                ('description_uz', models.TextField(blank=True, help_text='Qisqacha tavsif (kartochka uchun)', null=True)),
                ('description_ru', models.TextField(blank=True, help_text='Qisqacha tavsif (kartochka uchun)', null=True)),
                ('description_en', models.TextField(blank=True, help_text='Qisqacha tavsif (kartochka uchun)', null=True)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text="To'liq mazmun (batafsil sahifa uchun)")),
                ('content_uz', wagtail.fields.RichTextField(blank=True, help_text="To'liq mazmun (batafsil sahifa uchun)", null=True)),
                ('content_ru', wagtail.fields.RichTextField(blank=True, help_text="To'liq mazmun (batafsil sahifa uchun)", null=True)),
                ('content_en', wagtail.fields.RichTextField(blank=True, help_text="To'liq mazmun (batafsil sahifa uchun)", null=True)),
                ('icon', models.CharField(blank=True, help_text='Ikonka emoji yoki CSS klassi (masalan: 🧠)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Klub uchun muqova rasm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Klub',
                'verbose_name_plural': 'Klublar',
                'ordering': ['order', 'name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='EnlightenmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Bo'lim sarlavhasi", max_length=255)),
                ('title_uz', models.CharField(help_text="Bo'lim sarlavhasi", max_length=255, null=True)),
                ('title_ru', models.CharField(help_text="Bo'lim sarlavhasi", max_length=255, null=True)),
                ('title_en', models.CharField(help_text="Bo'lim sarlavhasi", max_length=255, null=True)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text="Bo'lim mazmuni")),
                ('content_uz', wagtail.fields.RichTextField(blank=True, help_text="Bo'lim mazmuni", null=True)),
                ('content_ru', wagtail.fields.RichTextField(blank=True, help_text="Bo'lim mazmuni", null=True)),
                ('content_en', wagtail.fields.RichTextField(blank=True, help_text="Bo'lim mazmuni", null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ForeignKey(blank=True, help_text="Bo'lim uchun rasm", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': "Ma'rifat bo'limi",
                'verbose_name_plural': "Ma'rifat bo'limlari",
                'ordering': ['order', 'title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
