# Generated by Django 5.2.12 on 2026-03-14 06:17

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(help_text='Qisqa tavsif (karta uchun)')),
                ('description_uz', models.TextField(help_text='Qisqa tavsif (karta uchun)', null=True)),
                ('description_ru', models.TextField(help_text='Qisqa tavsif (karta uchun)', null=True)),
                ('description_en', models.TextField(help_text='Qisqa tavsif (karta uchun)', null=True)),
                ('icon_svg', models.TextField(blank=True, help_text='SVG kod yoki icon nomi')),
                ('theme_color', models.CharField(default='from-blue-500 to-indigo-600', help_text='Tailwind color class (masalan: from-blue-500 to-indigo-600)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Tadqiqot yo'nalishi",
                'verbose_name_plural': "Tadqiqot yo'nalishlari",
                'ordering': ['order', 'title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ResearchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(help_text='Kichik sarlavha', max_length=255)),
                ('subtitle_uz', models.CharField(help_text='Kichik sarlavha', max_length=255, null=True)),
                ('subtitle_ru', models.CharField(help_text='Kichik sarlavha', max_length=255, null=True)),
                ('subtitle_en', models.CharField(help_text='Kichik sarlavha', max_length=255, null=True)),
                ('content', wagtail.fields.RichTextField(help_text="Batafsil ma'lumot (Rich Text)")),
                ('content_uz', wagtail.fields.RichTextField(help_text="Batafsil ma'lumot (Rich Text)", null=True)),
                ('content_ru', wagtail.fields.RichTextField(help_text="Batafsil ma'lumot (Rich Text)", null=True)),
                ('content_en', wagtail.fields.RichTextField(help_text="Batafsil ma'lumot (Rich Text)", null=True)),
                ('stat1_label', models.CharField(max_length=100)),
                ('stat1_label_uz', models.CharField(max_length=100, null=True)),
                ('stat1_label_ru', models.CharField(max_length=100, null=True)),
                ('stat1_label_en', models.CharField(max_length=100, null=True)),
                ('stat1_value', models.CharField(max_length=50)),
                ('stat2_label', models.CharField(max_length=100)),
                ('stat2_label_uz', models.CharField(max_length=100, null=True)),
                ('stat2_label_ru', models.CharField(max_length=100, null=True)),
                ('stat2_label_en', models.CharField(max_length=100, null=True)),
                ('stat2_value', models.CharField(max_length=50)),
                ('stat3_label', models.CharField(max_length=100)),
                ('stat3_label_uz', models.CharField(max_length=100, null=True)),
                ('stat3_label_ru', models.CharField(max_length=100, null=True)),
                ('stat3_label_en', models.CharField(max_length=100, null=True)),
                ('stat3_value', models.CharField(max_length=50)),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='science.researcharea')),
                ('main_image', models.ForeignKey(blank=True, help_text='Asosiy rasm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Tadqiqot tafsiloti',
                'verbose_name_plural': 'Tadqiqot tafsilotlari',
            },
        ),
        migrations.CreateModel(
            name='ScienceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sarlavha (masalan: Bilim va Innovatsiya Markazi)', max_length=255)),
                ('title_uz', models.CharField(help_text='Sarlavha (masalan: Bilim va Innovatsiya Markazi)', max_length=255, null=True)),
                ('title_ru', models.CharField(help_text='Sarlavha (masalan: Bilim va Innovatsiya Markazi)', max_length=255, null=True)),
                ('title_en', models.CharField(help_text='Sarlavha (masalan: Bilim va Innovatsiya Markazi)', max_length=255, null=True)),
                ('description', models.TextField(help_text='Asosiy tavsif')),
                ('description_uz', models.TextField(help_text='Asosiy tavsif', null=True)),
                ('description_ru', models.TextField(help_text='Asosiy tavsif', null=True)),
                ('description_en', models.TextField(help_text='Asosiy tavsif', null=True)),
                ('stat1_label', models.CharField(help_text='Statistika 1 nomi (masalan: Ilmiy xodimlar)', max_length=100)),
                ('stat1_label_uz', models.CharField(help_text='Statistika 1 nomi (masalan: Ilmiy xodimlar)', max_length=100, null=True)),
                ('stat1_label_ru', models.CharField(help_text='Statistika 1 nomi (masalan: Ilmiy xodimlar)', max_length=100, null=True)),
                ('stat1_label_en', models.CharField(help_text='Statistika 1 nomi (masalan: Ilmiy xodimlar)', max_length=100, null=True)),
                ('stat1_value', models.CharField(help_text='Statistika 1 qiymati (masalan: 150+)', max_length=50)),
                ('stat2_label', models.CharField(help_text='Statistika 2 nomi', max_length=100)),
                ('stat2_label_uz', models.CharField(help_text='Statistika 2 nomi', max_length=100, null=True)),
                ('stat2_label_ru', models.CharField(help_text='Statistika 2 nomi', max_length=100, null=True)),
                ('stat2_label_en', models.CharField(help_text='Statistika 2 nomi', max_length=100, null=True)),
                ('stat2_value', models.CharField(help_text='Statistika 2 qiymati', max_length=50)),
                ('stat3_label', models.CharField(help_text='Statistika 3 nomi', max_length=100)),
                ('stat3_label_uz', models.CharField(help_text='Statistika 3 nomi', max_length=100, null=True)),
                ('stat3_label_ru', models.CharField(help_text='Statistika 3 nomi', max_length=100, null=True)),
                ('stat3_label_en', models.CharField(help_text='Statistika 3 nomi', max_length=100, null=True)),
                ('stat3_value', models.CharField(help_text='Statistika 3 qiymati', max_length=50)),
                ('stat4_label', models.CharField(help_text='Statistika 4 nomi', max_length=100)),
                ('stat4_label_uz', models.CharField(help_text='Statistika 4 nomi', max_length=100, null=True)),
                ('stat4_label_ru', models.CharField(help_text='Statistika 4 nomi', max_length=100, null=True)),
                ('stat4_label_en', models.CharField(help_text='Statistika 4 nomi', max_length=100, null=True)),
                ('stat4_value', models.CharField(help_text='Statistika 4 qiymati', max_length=50)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Hero section uchun background rasm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Ilmiy faoliyat asosi',
                'verbose_name_plural': 'Ilmiy faoliyat asosi',
            },
        ),
    ]
