# Generated by Django 5.2.12 on 2026-03-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcharea',
            name='icon_svg',
        ),
        migrations.RemoveField(
            model_name='researcharea',
            name='theme_color',
        ),
    ]
