# Generated by Django 5.2.10 on 2026-03-03 12:14

import django.utils.timezone
import modelsearch.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="To'liq ism-sharif (F.I.O)", max_length=255)),
                ('email', models.EmailField(help_text='Elektron pochta manzili', max_length=254)),
                ('department', models.CharField(help_text="Fakultet / Bo'lim / Boshqa", max_length=255)),
                ('department_uz', models.CharField(help_text="Fakultet / Bo'lim / Boshqa", max_length=255, null=True)),
                ('department_ru', models.CharField(help_text="Fakultet / Bo'lim / Boshqa", max_length=255, null=True)),
                ('department_en', models.CharField(help_text="Fakultet / Bo'lim / Boshqa", max_length=255, null=True)),
                ('group_number', models.CharField(blank=True, help_text="Guruh raqami (agar talaba bo'lsangiz)", max_length=50)),
                ('phone', models.CharField(help_text='Telefon raqam', max_length=20)),
                ('message', models.TextField(help_text='Murojaat matni')),
                ('message_uz', models.TextField(help_text='Murojaat matni', null=True)),
                ('message_ru', models.TextField(help_text='Murojaat matni', null=True)),
                ('message_en', models.TextField(help_text='Murojaat matni', null=True)),
                ('terms_accepted', models.BooleanField(default=False, help_text='Murojaat yuborish qoidalarini qabul qilganmi?')),
                ('is_read', models.BooleanField(default=False, help_text="Admin ko'rganmi?")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Yuborilgan sana')),
            ],
            options={
                'verbose_name': 'Direktorga murojaat',
                'verbose_name_plural': 'Direktorga murojaatlar',
                'ordering': ['-created_at'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
