# Generated by Django 5.2.10 on 2026-02-16 06:27

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="To'liq ism-sharif, masalan: Abdullayev Sherzod Nematovich", max_length=255)),
                ('position', models.CharField(help_text="Lavozim, masalan: Rektor, Ilmiy ishlar bo'yicha prorektor", max_length=255)),
                ('academic_degree', models.CharField(help_text='Ilmiy daraja, masalan: Texnika fanlari doktori, Professor', max_length=255)),
                ('email', models.EmailField(help_text='Elektron pochta manzili', max_length=254)),
                ('phone', models.CharField(help_text='Telefon raqam', max_length=50)),
                ('reception_days', models.CharField(blank=True, help_text='Qabul kunlari, masalan: Dushanba-Juma 14:00-16:00', max_length=255)),
                ('bio', wagtail.fields.RichTextField(blank=True, help_text="Biografiya — qisqacha ma'lumot")),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi). Rektor = 0, prorektor = 1, 2, ...')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(help_text='Rahbar surati', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Rahbar',
                'verbose_name_plural': 'Rahbariyat',
                'ordering': ['order', 'full_name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
