# Generated by Django 5.2.10 on 2026-02-17 06:43

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Bo'lim nomi, masalan: Ilmiy ishlar bo'yicha prorektor", max_length=255)),
                ('slug', models.SlugField(help_text="URL uchun identifikator (avtomatik to'ldiriladi)", max_length=255, unique=True)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text="Bo'lim haqida qo'shimcha ma'lumot")),
                ('icon', models.CharField(blank=True, help_text='Ikonka CSS klassi yoki emoji (masalan: 🏛️ yoki fa-university)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, help_text="Bo'lim rahbari (Leader modelidan)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_sections', to='sections.leader')),
                ('parent', models.ForeignKey(blank=True, help_text="Yuqori bo'lim (bo'sh = asosiy bo'lim)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sections.structuresection')),
            ],
            options={
                'verbose_name': "Tuzilma bo'limi",
                'verbose_name_plural': 'Tuzilma',
                'ordering': ['order', 'name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='SectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="To'liq ism-sharif", max_length=255)),
                ('position', models.CharField(help_text='Lavozim', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Elektron pochta manzili', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Telefon raqam', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami')),
                ('image', models.ForeignKey(blank=True, help_text="A'zo surati", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('section', models.ForeignKey(help_text="Tegishli bo'lim", on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sections.structuresection')),
            ],
            options={
                'verbose_name': "Bo'lim a'zosi",
                'verbose_name_plural': "Bo'lim a'zolari",
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
