# Generated by Django 5.2.10 on 2026-02-18 05:40

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_structuresection_sectionmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='academic_degree',
            field=models.CharField(blank=True, help_text='Ilmiy daraja, masalan: Texnika fanlari doktori, Professor', max_length=255),
        ),
        migrations.AlterField(
            model_name='sectionmember',
            name='section',
            field=modelcluster.fields.ParentalKey(help_text="Tegishli bo'lim", on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sections.structuresection'),
        ),
    ]
