# Generated by Django 5.2.10 on 2026-02-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_leader_academic_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmember',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
