# Generated by Django 5.2.10 on 2026-03-03 08:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_sectionmember_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='academic_degree_en',
            field=models.CharField(blank=True, help_text='Ilmiy daraja, masalan: Texnika fanlari doktori, Professor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='academic_degree_ru',
            field=models.CharField(blank=True, help_text='Ilmiy daraja, masalan: Texnika fanlari doktori, Professor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='academic_degree_uz',
            field=models.CharField(blank=True, help_text='Ilmiy daraja, masalan: Texnika fanlari doktori, Professor', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='bio_en',
            field=wagtail.fields.RichTextField(blank=True, help_text="Biografiya — qisqacha ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='bio_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text="Biografiya — qisqacha ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='bio_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text="Biografiya — qisqacha ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='full_name_en',
            field=models.CharField(help_text="To'liq ism-sharif, masalan: Abdullayev Sherzod Nematovich", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='full_name_ru',
            field=models.CharField(help_text="To'liq ism-sharif, masalan: Abdullayev Sherzod Nematovich", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='full_name_uz',
            field=models.CharField(help_text="To'liq ism-sharif, masalan: Abdullayev Sherzod Nematovich", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_en',
            field=models.CharField(help_text="Lavozim, masalan: Rektor, Ilmiy ishlar bo'yicha prorektor", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_ru',
            field=models.CharField(help_text="Lavozim, masalan: Rektor, Ilmiy ishlar bo'yicha prorektor", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_uz',
            field=models.CharField(help_text="Lavozim, masalan: Rektor, Ilmiy ishlar bo'yicha prorektor", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='reception_days_en',
            field=models.CharField(blank=True, help_text='Qabul kunlari, masalan: Dushanba-Juma 14:00-16:00', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='reception_days_ru',
            field=models.CharField(blank=True, help_text='Qabul kunlari, masalan: Dushanba-Juma 14:00-16:00', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='reception_days_uz',
            field=models.CharField(blank=True, help_text='Qabul kunlari, masalan: Dushanba-Juma 14:00-16:00', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionmember',
            name='full_name_en',
            field=models.CharField(help_text="To'liq ism-sharif", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionmember',
            name='full_name_ru',
            field=models.CharField(help_text="To'liq ism-sharif", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionmember',
            name='full_name_uz',
            field=models.CharField(help_text="To'liq ism-sharif", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionmember',
            name='position_en',
            field=models.CharField(help_text='Lavozim', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionmember',
            name='position_ru',
            field=models.CharField(help_text='Lavozim', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sectionmember',
            name='position_uz',
            field=models.CharField(help_text='Lavozim', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='structuresection',
            name='description_en',
            field=wagtail.fields.RichTextField(blank=True, help_text="Bo'lim haqida qo'shimcha ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='structuresection',
            name='description_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text="Bo'lim haqida qo'shimcha ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='structuresection',
            name='description_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text="Bo'lim haqida qo'shimcha ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='structuresection',
            name='name_en',
            field=models.CharField(help_text="Bo'lim nomi, masalan: Ilmiy ishlar bo'yicha prorektor", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='structuresection',
            name='name_ru',
            field=models.CharField(help_text="Bo'lim nomi, masalan: Ilmiy ishlar bo'yicha prorektor", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='structuresection',
            name='name_uz',
            field=models.CharField(help_text="Bo'lim nomi, masalan: Ilmiy ishlar bo'yicha prorektor", max_length=255, null=True),
        ),
    ]
