# Generated by Django 5.2.12 on 2026-03-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HemisStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_count', models.IntegerField(default=0, verbose_name='Jami talabalar soni')),
                ('teachers_count', models.IntegerField(default=0, verbose_name="Jami o'qituvchilar soni")),
                ('efficiency', models.IntegerField(default=45, verbose_name='Natijadorlik (%)')),
                ('directions_count', models.IntegerField(default=9, verbose_name="Yo'nalishlar soni")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish vaqti')),
            ],
            options={
                'verbose_name': 'Hemis Statistikasi',
                'verbose_name_plural': 'Hemis Statistikalari',
            },
        ),
    ]
