# Generated by Django 5.2.10 on 2026-02-25 06:12

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Hamkorlik turi nomi, masalan: Xalqaro hamkor tashkilotlar', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL uchun identifikator (avtomatik yaratiladi)', max_length=255, unique=True)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text="Hamkorlik turi haqida umumiy ma'lumot")),
                ('icon', models.CharField(blank=True, help_text='Ikonka CSS klassi yoki emoji (masalan: 🌍 yoki fa-globe)', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Hamkorlik turi uchun muqova rasm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Hamkorlik turi',
                'verbose_name_plural': 'Hamkorlik turlari',
                'ordering': ['order', 'title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='PartnerOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hamkor tashkilot nomi', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL uchun identifikator (avtomatik yaratiladi)', max_length=255, unique=True)),
                ('country', models.CharField(blank=True, help_text='Davlat nomi (masalan: South Korea, Germany)', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Hamkor tashkilotning veb-sayti')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text="Hamkor tashkilot haqida batafsil ma'lumot")),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaboration_type', models.ForeignKey(help_text='Hamkorlik turi', on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='collaboration.collaborationtype')),
                ('logo', models.ForeignKey(blank=True, help_text='Hamkor tashkilot logotipi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Hamkor tashkilot',
                'verbose_name_plural': 'Hamkor tashkilotlar',
                'ordering': ['order', 'name'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='CollaborationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Loyiha sarlavhasi', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL uchun identifikator (avtomatik yaratiladi)', max_length=255, unique=True)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text="Loyiha haqida batafsil ma'lumot")),
                ('start_date', models.DateField(blank=True, help_text='Loyiha boshlanish sanasi', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Loyiha tugash sanasi', null=True)),
                ('external_link', models.URLField(blank=True, help_text='Tashqi loyiha sahifasiga havola')),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Loyiha uchun muqova rasm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('collaboration_type', models.ForeignKey(help_text='Hamkorlik turi', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='collaboration.collaborationtype')),
                ('partners', models.ManyToManyField(blank=True, help_text='Loyihada ishtirok etuvchi hamkor tashkilotlar', related_name='projects', to='collaboration.partnerorganization')),
            ],
            options={
                'verbose_name': 'Hamkorlik loyihasi',
                'verbose_name_plural': 'Hamkorlik loyihalari',
                'ordering': ['order', 'title'],
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
