# Generated by Django 5.2.10 on 2026-02-25 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganization',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Hamkorlik haqida muqova rasm (banner)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
