# Generated by Django 5.2.10 on 2026-02-28 04:01

import django.db.models.deletion
import modelsearch.index
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_partnerorganization_cover_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sahifa sarlavhasi', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL uchun identifikator (avtomatik yaratiladi)', max_length=255)),
                ('content', wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni')),
                ('order', models.PositiveIntegerField(default=0, help_text='Tartib raqami (0 = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (O'chirilsa saytda ko'rinmaydi)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaboration_type', models.ForeignKey(help_text='Tegishli hamkorlik turi', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='collaboration.collaborationtype')),
                ('cover_image', models.ForeignKey(blank=True, help_text='Sahifa uchun muqova rasm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('parent', models.ForeignKey(blank=True, help_text="Yuqori sahifa (bo'sh = hamkorlik turining to'g'ridan-to'g'ri bolasi)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='collaboration.collaborationpage')),
            ],
            options={
                'verbose_name': 'Hamkorlik sahifasi',
                'verbose_name_plural': 'Hamkorlik sahifalari',
                'ordering': ['order', 'title'],
                'unique_together': {('collaboration_type', 'slug')},
            },
            bases=(modelsearch.index.Indexed, models.Model),
        ),
    ]
