# Generated by Django 5.2.10 on 2026-03-03 08:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0003_collaborationpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationpage',
            name='content_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni', null=True),
        ),
        migrations.AddField(
            model_name='collaborationpage',
            name='content_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni', null=True),
        ),
        migrations.AddField(
            model_name='collaborationpage',
            name='content_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni', null=True),
        ),
        migrations.AddField(
            model_name='collaborationpage',
            name='title_en',
            field=models.CharField(help_text='Sahifa sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborationpage',
            name='title_ru',
            field=models.CharField(help_text='Sahifa sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborationpage',
            name='title_uz',
            field=models.CharField(help_text='Sahifa sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborationproject',
            name='content_en',
            field=wagtail.fields.RichTextField(blank=True, help_text="Loyiha haqida batafsil ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='collaborationproject',
            name='content_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text="Loyiha haqida batafsil ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='collaborationproject',
            name='content_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text="Loyiha haqida batafsil ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='collaborationproject',
            name='title_en',
            field=models.CharField(help_text='Loyiha sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborationproject',
            name='title_ru',
            field=models.CharField(help_text='Loyiha sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborationproject',
            name='title_uz',
            field=models.CharField(help_text='Loyiha sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborationtype',
            name='description_en',
            field=wagtail.fields.RichTextField(blank=True, help_text="Hamkorlik turi haqida umumiy ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='collaborationtype',
            name='description_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text="Hamkorlik turi haqida umumiy ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='collaborationtype',
            name='description_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text="Hamkorlik turi haqida umumiy ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='collaborationtype',
            name='title_en',
            field=models.CharField(help_text='Hamkorlik turi nomi, masalan: Xalqaro hamkor tashkilotlar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborationtype',
            name='title_ru',
            field=models.CharField(help_text='Hamkorlik turi nomi, masalan: Xalqaro hamkor tashkilotlar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collaborationtype',
            name='title_uz',
            field=models.CharField(help_text='Hamkorlik turi nomi, masalan: Xalqaro hamkor tashkilotlar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='country_en',
            field=models.CharField(blank=True, help_text='Davlat nomi (masalan: South Korea, Germany)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='country_ru',
            field=models.CharField(blank=True, help_text='Davlat nomi (masalan: South Korea, Germany)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='country_uz',
            field=models.CharField(blank=True, help_text='Davlat nomi (masalan: South Korea, Germany)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='description_en',
            field=wagtail.fields.RichTextField(blank=True, help_text="Hamkor tashkilot haqida batafsil ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='description_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text="Hamkor tashkilot haqida batafsil ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='description_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text="Hamkor tashkilot haqida batafsil ma'lumot", null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='name_en',
            field=models.CharField(help_text='Hamkor tashkilot nomi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='name_ru',
            field=models.CharField(help_text='Hamkor tashkilot nomi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partnerorganization',
            name='name_uz',
            field=models.CharField(help_text='Hamkor tashkilot nomi', max_length=255, null=True),
        ),
    ]
