# Generated by Django 5.2.10 on 2026-02-20 06:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Navigatsiya havola matni (masalan: Universitet)', max_length=200)),
                ('page_id', models.CharField(help_text='Frontend sahifa identifikatori (masalan: home, news, about)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Tartib raqami (kichik = birinchi)')),
                ('is_active', models.BooleanField(default=True, help_text="Faolmi? (o'chirilgan bo'lsa navbarda ko'rinmaydi)")),
            ],
            options={
                'verbose_name': 'Navigatsiya havola',
                'verbose_name_plural': 'Navigatsiya havolalar',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SubNavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Pastki havola matni (masalan: Filial haqida)', max_length=200)),
                ('page_id', models.CharField(help_text='Frontend sahifa identifikatori (masalan: about, leadership)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text='Faolmi?')),
                ('parent', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.navitem')),
            ],
            options={
                'verbose_name': 'Pastki havola',
                'verbose_name_plural': 'Pastki havolalar',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
