# Generated by Django 5.2.10 on 2026-02-20 06:58

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sahifa sarlavhasi', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL uchun identifikator (avtomatik yaratiladi)', max_length=255, unique=True)),
                ('body', wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni')),
                ('is_active', models.BooleanField(default=True, help_text='Faolmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dinamik sahifa',
                'verbose_name_plural': 'Dinamik sahifalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='navitem',
            name='page_id',
            field=models.CharField(blank=True, choices=[('', '— Tanlang —'), ('home', 'Bosh sahifa'), ('about', 'Filial haqida'), ('leadership', 'Rahbariyat'), ('structure', 'Tuzilma'), ('vacancies', "Bo'sh ish o'rinlari"), ('education', "O'quv faoliyati"), ('faculties', 'Fakultetlar'), ('departments', 'Kafedralar'), ('science', 'Ilmiy faoliyat'), ('spirituality', "Ma'naviy faoliyat"), ('international', 'Xalqaro hamkorlik'), ('admission', 'Qabul'), ('distance-learning', "Masofaviy ta'lim"), ('library', 'Kutubxona'), ('systems', 'Elektron tizimlar'), ('payment', "To'lov-kontrakt"), ('news', 'Yangiliklar'), ('announcements', "E'lonlar")], default='', help_text='Mavjud sahifaga havola', max_length=100),
        ),
        migrations.AlterField(
            model_name='subnavitem',
            name='page_id',
            field=models.CharField(blank=True, choices=[('', '— Tanlang —'), ('home', 'Bosh sahifa'), ('about', 'Filial haqida'), ('leadership', 'Rahbariyat'), ('structure', 'Tuzilma'), ('vacancies', "Bo'sh ish o'rinlari"), ('education', "O'quv faoliyati"), ('faculties', 'Fakultetlar'), ('departments', 'Kafedralar'), ('science', 'Ilmiy faoliyat'), ('spirituality', "Ma'naviy faoliyat"), ('international', 'Xalqaro hamkorlik'), ('admission', 'Qabul'), ('distance-learning', "Masofaviy ta'lim"), ('library', 'Kutubxona'), ('systems', 'Elektron tizimlar'), ('payment', "To'lov-kontrakt"), ('news', 'Yangiliklar'), ('announcements', "E'lonlar")], default='', help_text='Mavjud sahifaga havola', max_length=100),
        ),
        migrations.AddField(
            model_name='navitem',
            name='linked_page',
            field=models.ForeignKey(blank=True, help_text='Dinamik sahifaga havola (yangi sahifa uchun)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items', to='navigation.dynamicpage'),
        ),
        migrations.AddField(
            model_name='subnavitem',
            name='linked_page',
            field=models.ForeignKey(blank=True, help_text='Dinamik sahifaga havola (yangi sahifa uchun)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_nav_items', to='navigation.dynamicpage'),
        ),
    ]
