# Generated by Django 5.2.10 on 2026-02-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('navigation', '0002_dynamicpage_alter_navitem_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navitem',
            name='linked_activity_category',
            field=models.ForeignKey(blank=True, help_text='Faoliyat kategoriyasiga havola', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_items', to='activities.activitycategory'),
        ),
        migrations.AddField(
            model_name='subnavitem',
            name='linked_activity_category',
            field=models.ForeignKey(blank=True, help_text='Faoliyat kategoriyasiga havola', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_nav_items', to='activities.activitycategory'),
        ),
        migrations.AlterField(
            model_name='navitem',
            name='page_id',
            field=models.CharField(blank=True, choices=[('', '— Tanlang —'), ('home', 'Bosh sahifa'), ('about', 'Filial haqida'), ('leadership', 'Rahbariyat'), ('structure', 'Tuzilma'), ('vacancies', "Bo'sh ish o'rinlari"), ('education', "O'quv faoliyati"), ('faculties', 'Fakultetlar'), ('departments', 'Kafedralar'), ('science', 'Ilmiy faoliyat'), ('spirituality', "Ma'naviy faoliyat"), ('international', 'Xalqaro hamkorlik'), ('admission', 'Qabul'), ('distance-learning', "Masofaviy ta'lim"), ('library', 'Kutubxona'), ('systems', 'Elektron tizimlar'), ('payment', "To'lov-kontrakt"), ('news', 'Yangiliklar'), ('announcements', "E'lonlar"), ('activities', 'Faoliyatlar')], default='', help_text='Mavjud sahifaga havola', max_length=100),
        ),
        migrations.AlterField(
            model_name='subnavitem',
            name='page_id',
            field=models.CharField(blank=True, choices=[('', '— Tanlang —'), ('home', 'Bosh sahifa'), ('about', 'Filial haqida'), ('leadership', 'Rahbariyat'), ('structure', 'Tuzilma'), ('vacancies', "Bo'sh ish o'rinlari"), ('education', "O'quv faoliyati"), ('faculties', 'Fakultetlar'), ('departments', 'Kafedralar'), ('science', 'Ilmiy faoliyat'), ('spirituality', "Ma'naviy faoliyat"), ('international', 'Xalqaro hamkorlik'), ('admission', 'Qabul'), ('distance-learning', "Masofaviy ta'lim"), ('library', 'Kutubxona'), ('systems', 'Elektron tizimlar'), ('payment', "To'lov-kontrakt"), ('news', 'Yangiliklar'), ('announcements', "E'lonlar"), ('activities', 'Faoliyatlar')], default='', help_text='Mavjud sahifaga havola', max_length=100),
        ),
    ]
