# Generated by Django 5.2.10 on 2026-03-03 08:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_navitem_linked_activity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpage',
            name='body_en',
            field=wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni', null=True),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='body_ru',
            field=wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni', null=True),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='body_uz',
            field=wagtail.fields.RichTextField(blank=True, help_text='Sahifa mazmuni', null=True),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='title_en',
            field=models.CharField(help_text='Sahifa sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='title_ru',
            field=models.CharField(help_text='Sahifa sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='title_uz',
            field=models.CharField(help_text='Sahifa sarlavhasi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='navitem',
            name='title_en',
            field=models.CharField(help_text='Navigatsiya havola matni (masalan: Universitet)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='navitem',
            name='title_ru',
            field=models.CharField(help_text='Navigatsiya havola matni (masalan: Universitet)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='navitem',
            name='title_uz',
            field=models.CharField(help_text='Navigatsiya havola matni (masalan: Universitet)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subnavitem',
            name='title_en',
            field=models.CharField(help_text='Pastki havola matni (masalan: Filial haqida)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subnavitem',
            name='title_ru',
            field=models.CharField(help_text='Pastki havola matni (masalan: Filial haqida)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subnavitem',
            name='title_uz',
            field=models.CharField(help_text='Pastki havola matni (masalan: Filial haqida)', max_length=200, null=True),
        ),
    ]
