# Generated by Django 5.2.12 on 2026-03-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_dynamicpage_body_en_dynamicpage_body_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subnavitem',
            options={'ordering': ['order', 'pk'], 'verbose_name': 'Ichki havola', 'verbose_name_plural': 'Ichki havolalar'},
        ),
        migrations.AlterField(
            model_name='navitem',
            name='page_id',
            field=models.CharField(blank=True, choices=[('', '— Tanlang —'), ('home', 'Bosh sahifa'), ('about', 'Filial haqida'), ('leadership', 'Rahbariyat'), ('structure', 'Tuzilma'), ('vacancies', "Bo'sh ish o'rinlari"), ('education', "O'quv faoliyati"), ('faculties', 'Fakultetlar'), ('departments', 'Kafedralar'), ('science', 'Ilmiy faoliyat'), ('spirituality', "Ma'naviy faoliyat"), ('international', 'Xalqaro hamkorlik'), ('admission', 'Qabul'), ('distance-learning', "Masofaviy ta'lim"), ('library', 'Kutubxona'), ('systems', 'Elektron tizimlar'), ('payment', "To'lov-kontrakt"), ('news', 'Yangiliklar'), ('announcements', "E'lonlar"), ('activities', 'Faoliyatlar'), ('appeal-director', 'Direktoga murojaat')], default='', help_text='Mavjud sahifaga havola', max_length=100),
        ),
        migrations.AlterField(
            model_name='subnavitem',
            name='page_id',
            field=models.CharField(blank=True, choices=[('', '— Tanlang —'), ('home', 'Bosh sahifa'), ('about', 'Filial haqida'), ('leadership', 'Rahbariyat'), ('structure', 'Tuzilma'), ('vacancies', "Bo'sh ish o'rinlari"), ('education', "O'quv faoliyati"), ('faculties', 'Fakultetlar'), ('departments', 'Kafedralar'), ('science', 'Ilmiy faoliyat'), ('spirituality', "Ma'naviy faoliyat"), ('international', 'Xalqaro hamkorlik'), ('admission', 'Qabul'), ('distance-learning', "Masofaviy ta'lim"), ('library', 'Kutubxona'), ('systems', 'Elektron tizimlar'), ('payment', "To'lov-kontrakt"), ('news', 'Yangiliklar'), ('announcements', "E'lonlar"), ('activities', 'Faoliyatlar'), ('appeal-director', 'Direktoga murojaat')], default='', help_text='Mavjud sahifaga havola', max_length=100),
        ),
        migrations.AlterField(
            model_name='subnavitem',
            name='title',
            field=models.CharField(help_text='Ichki havola matni (masalan: Filial haqida)', max_length=200),
        ),
        migrations.AlterField(
            model_name='subnavitem',
            name='title_en',
            field=models.CharField(help_text='Ichki havola matni (masalan: Filial haqida)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subnavitem',
            name='title_ru',
            field=models.CharField(help_text='Ichki havola matni (masalan: Filial haqida)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subnavitem',
            name='title_uz',
            field=models.CharField(help_text='Ichki havola matni (masalan: Filial haqida)', max_length=200, null=True),
        ),
    ]
