# Generated by Django 5.2.12 on 2026-03-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_alter_subnavitem_options_alter_navitem_page_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Havola matni (masalan: Elektron pochta)', max_length=200)),
                ('title_uz', models.CharField(help_text='Havola matni (masalan: Elektron pochta)', max_length=200, null=True)),
                ('title_ru', models.CharField(help_text='Havola matni (masalan: Elektron pochta)', max_length=200, null=True)),
                ('title_en', models.CharField(help_text='Havola matni (masalan: Elektron pochta)', max_length=200, null=True)),
                ('url', models.URLField(help_text='Murojaat qilinadigan manzil (URL)', max_length=500)),
                ('order', models.IntegerField(default=0, help_text='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, help_text='Faolmi?')),
            ],
            options={
                'verbose_name': 'TopBar havolasi',
                'verbose_name_plural': 'TopBar havolalari',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
