# Generated by Django 5.2.12 on 2026-03-20 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_topbarlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topbarlink',
            name='url',
        ),
        migrations.AddField(
            model_name='topbarlink',
            name='linked_page',
            field=models.ForeignKey(blank=True, help_text='Dinamik sahifaga havola', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topbar_links', to='navigation.dynamicpage'),
        ),
    ]
